### ISSUE TITLE
List item binding deletion - meta value out of sync

### ISSUE THREAD

**Issue by aholik** [moreartyjs/moreartyjs#45] opened 2015-01-16 21:43 UTC
When deleting a list item which has an assigned meta value, the meta value wont deleted. Instead it will bound to the same index:

```js
var ctx = Morearty.createContext({
  initialState: {
    items: ["foo", "bar", "baz"]
  }
});

var b = ctx.getBinding().sub("items");

b.sub(1).meta().set("bar-meta");
console.log(b.sub(1).toJS(), b.sub(1).meta().toJS());    // bar bar-meta

// let`s remove bar
b.delete(1);
console.log(b.sub(1).toJS(), b.sub(1).meta().toJS());    // baz bar-meta
```

Is this by design? In my interpretation meta bindings are depend on their parent binding, so when deleting a binding I expect it's meta binding to be deleted, too.

**Comment by mbektimirov** [comment] 2015-01-16 22:33
It is by design now, but you're right, it works not as expected by default. Meta is just another instance of additional state. We will discuss another approaches to work with meta, thank you.

**Comment by aholik** [comment] 2015-01-17 08:54
Yeah, I suspected it is not a bug. However than the api is not consistent, I mean when deleting a mapping node on some path the operation will remove the meta binding on the same path, too.

Anyway, I can live with it now with explicitly removing list item metas. Thanks.

**Comment by Tvaroh** [comment] 2015-01-17 13:52
Yep, this is to simplify implementation and improve performance. Can you clarify what you mean by deleting a mapping node?

**Comment by aholik** [comment] 2015-01-17 14:24
Sure, sorry, I used an inappropriate term here. I meant when you delete a key of a Map which has a meta binding attached, the meta binding won't exist on the same path after deletion.

But now after verifying my assumptions it turned out I was wrong:
```js
var ctx = Morearty.createContext({ 
  initialState: { dict: { "foo": "bar" } }});
var b = ctx.getBinding();

b.sub("dict.foo").meta().set("foo-meta");
console.log(b.sub("dict.foo").toJS(), b.sub("dict.foo").meta().toJS()); // bar foo-meta
b.delete("dict.foo");
console.log(b.sub("dict.foo").toJS(), b.sub("dict.foo").meta().toJS()); // undefined 'foo-meta'
```

So, the api is consistent, it seems that my impressions came from that my codes were working as expected only by coincidence.

**Comment by Tvaroh** [comment] 2015-01-17 16:02
Yes, that's correct. State and meta-state are never synchronized automatically.

**Comment by Tvaroh** [comment] 2015-01-19 07:37
Wiki [updated](https://github.com/moreartyjs/moreartyjs/wiki/Binding#attaching-meta-information). Since this behavior is by design let's close this.

**Closed by Tvaroh** 2015-01-19 07:37 UTC

**Comment by aholik** [comment] 2015-01-19 07:48
Great, thank you!
